SELECT U.USER_ID,U.NICKNAME,SUM(PRICE) AS TOTAL_SALES
FROM USED_GOODS_BOARD AS B
    INNER JOIN USED_GOODS_USER AS U
    ON B.WRITER_ID = U.USER_ID
WHERE STATUS = 'DONE'
GROUP BY B.WRITER_ID
HAVING TOTAL_SALES >=700000
ORDER BY 3 ASC;