SELECT I.ITEM_ID,ITEM_NAME,RARITY
FROM ITEM_INFO AS I,ITEM_TREE AS T
WHERE I.ITEM_ID=T.ITEM_ID 
AND T.parent_item_id in (select Item_ID from ITEM_INFO where RARITY ='RARE')
order BY I.ITEM_ID DESC;

# SELECT INFO.ITEMID, INFO.ITEMNAME, INFO.RARITY
# FROM ITEMINFO INFO, ITEMTREE TREE
# WHERE INFO.ITEMID = TREE.ITEMID
# AND TREE.PARENTITEMID IN
# (SELECT ITEMINFO.ITEMID FROM ITEMINFO WHERE ITEMINFO.RARITY = 'RARE')
# ORDER BY INFO.ITEM_ID DESC;