SELECT I.ITEM_ID,ITEM_NAME,RARITY
FROM ITEM_INFO AS I,ITEM_TREE AS T
WHERE I.ITEM_ID=T.ITEM_ID 
AND T.parent_item_id in (select Item_ID from ITEM_INFO where RARITY ='RARE')
order BY I.ITEM_ID DESC;

# SELECT TEMP.ITEM_ID, ITEM_NAME, RARITY
# FROM (
#     SELECT IT.ITEM_ID
#     FROM ITEM_INFO AS II
#     LEFT JOIN ITEM_TREE AS IT ON II.ITEM_ID = IT.PARENT_ITEM_ID
#     WHERE RARITY = 'RARE' AND IT.ITEM_ID IS NOT NULL) 
#     AS TEMP
# LEFT JOIN ITEM_INFO AS II2 ON TEMP.ITEM_ID = II2.ITEM_ID
# ORDER BY 1 DESC