SELECT YEAR(DIFFERENTIATION_DATE) AS YEAR, (MAXSIZEOFCOLONY - SIZE_OF_COLONY) AS YEAR_DEV
, ID
FROM (
    SELECT
    DIFFERENTIATION_DATE
    , SIZE_OF_COLONY
    , MAX(SIZE_OF_COLONY) OVER (PARTITION BY year(DIFFERENTIATION_DATE)) AS MAXSIZEOFCOLONY
    , ID
    FROM ECOLI_DATA
    ) AS A
ORDER BY YEAR, YEAR_DEV ASC